FROM openjdk:17-slim

# Python 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev build-essential librdkafka-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install https://www.pandas-ta.dev/assets/zip/pandas_ta-0.3.14b.tar.gz yfinance

COPY . .
RUN mkdir -p logs

CMD ["python3", "data_consumers/consume_kafka_batch.py"]
