apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-data
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
