replicaCount: 3

image:
  repository: bitnamilegacy/kafka
  tag: latest
  pullPolicy: IfNotPresent
  
kraft:
  enabled: true

controller:
  replicaCount: 3
  advertisedListeners:
    - name: CLIENT
      advertisedHost: localhost
      advertisedPort: 30092

listeners:
  client:
    protocol: PLAINTEXT
    port: 9092
  internal:
    protocol: PLAINTEXT
    port: 9093

configurationOverrides:
  log.retention.hours: 24
  auto.create.topics.enable: true

service:
  type: NodePort
  nodePorts:
    client: 30092

extraEnvVars:
  - name: KAFKA_CFG_LISTENERS
    value: PLAINTEXT://:9092