replicaCount: 3

image:
  repository: bitnamilegacy/kafka
  tag: latest
  pullPolicy: IfNotPresent

kraft:
  enabled: true

controller:
  replicaCount: 3

listeners:
  client:
    protocol: PLAINTEXT
    port: 9092
  internal:
    protocol: PLAINTEXT
    port: 9093

configurationOverrides:
  log.retention.hours: 24
