replicaCount: 3

image:
  repository: bitnamilegacy/kafka
  tag: latest
  pullPolicy: IfNotPresent
  
kraft:
  enabled: true  # ✅ KRaft 모드 사용 (Zookeeper 불필요)

zookeeper:
  enabled: false  # ✅ Zookeeper 비활성화

controller:
  replicaCount: 3

# ✅ 리스너 설정 수정
listeners:
  client:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

externalAccess:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        - 30092
        - 30093
        - 30094
    domain: localhost

# ✅ 불필요한 설정 제거 (충돌 방지)
# configurationOverrides, extraEnvVars는 externalAccess와 충돌할 수 있으므로 제거

service:
  type: ClusterIP  # ✅ NodePort는 externalAccess에서 처리

extraVolumes:
  - name: kafka-host-data
    hostPath:
      path: /opt/kafka-on-k3d
      type: DirectoryOrCreate  # ✅ 디렉터리가 없으면 자동 생성

extraVolumeMounts:
  - name: kafka-host-data
    mountPath: /mnt/kafka-on-k3d
    readOnly: false