replicaCount: 3

image:
  repository: bitnamilegacy/kafka
  tag: latest
  pullPolicy: IfNotPresent
  
kraft:
  enabled: true

controller:
  replicaCount: 3

listeners:
  client:
    protocol: PLAINTEXT
    port: 9092
  internal:
    protocol: PLAINTEXT
    port: 9093

configurationOverrides:
  log.retention.hours: 24

  # ✅ 각 브로커별 advertised.listeners 지정
  advertised.listeners: >-
    PLAINTEXT://kafka-0.localhost:30092,
    PLAINTEXT://kafka-1.localhost:30093,
    PLAINTEXT://kafka-2.localhost:30094
  listener.security.protocol.map: PLAINTEXT:PLAINTEXT
  listeners: PLAINTEXT://:9092

  # ✅ 자동 토픽 생성
  auto.create.topics.enable: true

service:
  type: NodePort
  nodePorts:
    client: 30092
    internal: 30093
    controller: 30094
