replicaCount: 3

image:
  repository: bitnamilegacy/kafka
  tag: latest
  pullPolicy: IfNotPresent
  
kraft:
  enabled: true

controller:
  replicaCount: 3

listeners:
  client:
    protocol: PLAINTEXT
    port: 9092
  internal:
    protocol: PLAINTEXT
    port: 9093

configurationOverrides:
  log.retention.hours: 24
  auto.create.topics.enable: true

service:
  type: NodePort
  nodePorts:
    client: 30092

# ✅ 환경변수 기반 강제 설정
# extraEnvVars:
#   - name: KAFKA_CFG_ADVERTISED_LISTENERS
#     value: PLAINTEXT://localhost:30092
#   - name: KAFKA_CFG_LISTENERS
#     value: PLAINTEXT://:9092
#   - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
#     value: PLAINTEXT:PLAINTEXT
