services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: >
      bash -c "start-master.sh && tail -f /dev/null"
    ports:
      - "8085:8080"   # Master UI 포트 변경
      - "7077:7077"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
    networks:
      - spark-network

  spark-worker-1:
    image: apache/spark:3.5.0
    container_name: spark-worker-1
    command: >
      bash -c "start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    ports:
      - "8086:8081"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: apache/spark:3.5.0
    container_name: spark-worker-2
    command: >
      bash -c "start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    ports:
      - "8087:8081"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network: